# Generated by Django 6.0.2 on 2026-03-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_logincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.ballot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.user')),
            ],
        ),
        migrations.AlterField(
            model_name='voteselection',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voterecord'),
        ),
    ]
