# Generated by Django 6.0.2 on 2026-03-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voterecord_alter_voteselection_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteselection',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.vote'),
        ),
    ]
